[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    ".pytest_cache"
]

[tool.pylint]
max-line-length = 120

[tool.black]
line-length = 120
target-version = ['py38']
